### ISSUE TITLE
cannot find .dll file

### ISSUE THREAD

**Issue by sommmen** [jburzynski/TypeGen#106]
Check this:

```
`dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 53.98 ms for C:\.....\MyProj.Interface\MyProj.Interface.csproj.
  MyProj.Interface -> C:\.....\MyProj.Interface\bin\Debug\netstandard2.0\Company.MyProj.Interface.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.63

C:\.....\MyProj.Interface>dotnet-typegen generate
APPLICATION ERROR: None of: 'MyProj.Interface.dll' or 'MyProj.Interface.exe' found in the default assembly folder (the project's bin\ folder; searched recursively). Please make sure your project is built.`
```

As you can see its looking for `MyProj.Interface.dll` but the output of the project creates: `Company.MyProj.Interface.dll`. We explicitely add `Company` like so;

![image](https://user-images.githubusercontent.com/8641495/81815665-8cb41a80-952a-11ea-9638-4091e6c80c2b.png)

And i gues that breakes the app.

Full stack trace;
```
APPLICATION ERROR: None of: 'WebHmi.Interface.dll' or 'WebHmi.Interface.exe' found in the default assembly folder (the project's bin\ folder; searched recursively). Please make sure your project is built.
   at TypeGen.Cli.Business.ConfigProvider.GetDefaultAssemblyPath(String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 123
   at TypeGen.Cli.Business.ConfigProvider.GetAssemblyPath(String configAssemblyPath, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 95
   at TypeGen.Cli.Business.ConfigProvider.UpdateConfigAssemblyPaths(TgConfig config, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 75
   at TypeGen.Cli.Business.ConfigProvider.GetConfig(String configPath, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 48
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 112
   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 70
```

**Comment by sommmen** [comment]
looking at https://github.com/jburzynski/TypeGen/blob/ce026b8498d738a277ddf4c01a0a191af6667a0c/src/TypeGen/TypeGen.Cli/Business/ConfigProvider.cs#L98

I see that you generate the output path based on a naming convention. Perhaps allow an extra parameter so we can select our own dll(s)? 

Or read the assembly name from the .csproj file?

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Company.MyApp.Interface</RootNamespace>
    <AssemblyName>Company.MyApp.Interface</AssemblyName>
  </PropertyGroup>

</Project>

```

**Comment by sommmen** [comment]
Also; my compliments for this very clear error message!
