### ISSUE TITLE
.NET 6 project,  Could not load type 'System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute'

### ISSUE THREAD

**Issue by mqudsi** [jburzynski/TypeGen#120]
Hello,

I've used TypeGen years ago but am unable to get it working in a .NET 6 project. The NuGet package installed ok, and I'm not trying to transpile any DTOs that contain .NET6-specific types. Just running `TypeGen` or `dotnet dotnet-typegen generate` gives the following error:

```
Generating files for project "CrowdHosted"...
GENERIC ERROR: Could not load type 'System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute' from assembly 'Sys
tem.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstant
iationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodAr
guments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, Runt
imeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListB
uilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& is
VarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int3
2 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at TypeGen.Core.Metadata.AttributeMetadataReader.GetAttribute[TAttribute](Type type) in D:\Google Drive\Projects\type-g
en\src\TypeGen\TypeGen.Core\Metadata\AttributeMetadataReader.cs:line 13
   at TypeGen.Core.Extensions.TypeExtensions.HasExportAttribute(Type type, IMetadataReader reader) in D:\Google Drive\Proj
ects\type-gen\src\TypeGen\TypeGen.Core\Extensions\TypeExtensions.cs:line 26
   at TypeGen.Core.Extensions.TypeExtensions.<>c__DisplayClass1_0.<GetExportMarkedTypes>b__0(Type t) in D:\Google Drive\Pr
ojects\type-gen\src\TypeGen\TypeGen.Core\Extensions\TypeExtensions.cs:line 42
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at TypeGen.Core.Generator.Services.GenerationSpecProvider.GetGenerationSpec(IEnumerable`1 assemblies) in D:\Google Driv
e\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator\Services\GenerationSpecProvider.cs:line 28
   at TypeGen.Core.Generator.Generator.Generate(IEnumerable`1 assemblies) in D:\Google Drive\Projects\type-gen\src\TypeGen
\TypeGen.Core\Generator\Generator.cs:line 341
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in D:\Google Drive\Projects\type-gen\src\TypeG
en\TypeGen.Cli\Program.cs:line 137
   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line
 70
```

Is this expected until the package is updated for .NET 6?

**Comment by cecbr** [comment]
I have the same isse. Please, when an update to NET 6 will be available?

**Comment by rametta** [comment]
I've opened a PR to upgrade to NET 6, hopefully it gets merged soon https://github.com/jburzynski/TypeGen/pull/122

**Comment by jburzynski** [comment]
Thanks for the PR, I added it to version 2.5.2, so it should support .NET 6.0.
