### ISSUE TITLE
APPLICATION ERROR: Generated type must be either a C# class or enum. Error when generating type System.RuntimeMethodHandle

### ISSUE THREAD

**Issue by parksj10** [jburzynski/TypeGen#136]
I'm having an error coming up... full stack below. I'm fairly certain it's because of a library I'm using `dotnetify`. When I add class to my project

```csharp
// ViewModelBase.cs

using DotNetify;

namespace FluxusApp.ViewModels
{
    public class ViewModelBase : BaseVM
    {
        private bool _isLoading;

        public ViewModelBase()
        {
            _isLoading = false;
        }

        /// <summary>
        ///     If the view is loading
        /// </summary>
        public bool IsLoading
        {
            get => _isLoading;
            set
            {
                // force send as async will require this.
                _isLoading = value;
                PushUpdates(true);
            }
        }
    }
}
```

and configure the generator spec:

```csharp
//GeneratorSpec.cs
using TypeGen.Core.SpecGeneration;
using FluxusApp.ViewModels;
using System;

namespace FluxusApp
{
    public class VMGenerationSpec : GenerationSpec
    {
        public VMGenerationSpec()
        {
            AddClass<ViewModelBase>();
        }
    }
}

```

I actually don't need anything in `BaseVM` from `dotnetify`, but I'm unsure how to exclude it only... I've tried `.IgnoreBase()` and it will generate, however I don't get the base class then.

Any suggestions?

```
APPLICATION ERROR: Generated type must be either a C# class or enum. Error when generating type System.RuntimeMethodHandle
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 395
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateInterface(Type type, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 417
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 387
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateInterface(Type type, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 417
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 387
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateNotMarked(Type type, String outputDirectory) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 382
   at TypeGen.Core.Generator.Generator.GenerateTypeDependencies(Type type, String outputDir) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 719
   at TypeGen.Core.Generator.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 423
   at TypeGen.Core.Generator.Generator.GenerateClass(Type type, ExportTsClassAttribute classAttribute) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 406
   at TypeGen.Core.Generator.Generator.GenerateType(Type type) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 284
   at TypeGen.Core.Generator.Generator.GenerateTypeInit(Type type) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 258
   at TypeGen.Core.Generator.Generator.Generate(IEnumerable`1 generationSpecs) in C:\projects\typegen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 157
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in C:\projects\typegen\src\TypeGen\TypeGen.Cli\Program.cs:line 151
   at TypeGen.Cli.Program.Main(String[] args) in C:\projects\typegen\src\TypeGen\TypeGen.Cli\Program.cs:line 77
```

**Comment by jburzynski** [comment]
If you need to keep BaseVM as a base class in TS, but you don't want to generate it, you can try using `AddClass<ViewModelBase>().IgnoreBase().CustomBase(...)`. This will override the default base class behaviour with the information in `CustomBase()`, but `IgnoreBase()` will also prevent the base type from being generated. I already forgot that this is how it works, but that's what the [documentation](https://typegen.readthedocs.io/en/latest/attributes.html#tscustombaseattribute) says.

**Comment by parksj10** [comment]
This does it! thanks a lot
