### ISSUE TITLE
Not able to install with Nuget on <TargetFramework>net6.0-windows</TargetFramework>

### ISSUE THREAD

**Issue by AHorak** [jburzynski/TypeGen#139]
dotnet-typegen Version 3.1.0 with Visual Studio 2022 fails

> Package dotnet-typegen 3.1.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package dotnet-typegen 3.1.0 supports: net6.0 (.NETCoreApp,Version=v6.0) / any

This is a Webapplication with React-Client.
How can i install it?

**Comment by AHorak** [comment]
TypeGenNG can be installed.
But it has some problems when calling ist in the Package Manager Console ...

`
...
Assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' found in: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.10\System.Runtime.dll
GENERIC ERROR: Could not load type 'System.CodeDom.Compiler.GeneratedCodeAttribute' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at TypeGen.Core.Metadata.AttributeMetadataReader.GetAttribute[TAttribute](Type type) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Core\Metadata\AttributeMetadataReader.cs:line 13
   at TypeGen.Core.Extensions.TypeExtensions.HasExportAttribute(Type type, IMetadataReader reader) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Core\Extensions\TypeExtensions.cs:line 26
   at TypeGen.Core.Extensions.TypeExtensions.<>c__DisplayClass1_0.<GetExportMarkedTypes>b__0(Type t) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Core\Extensions\TypeExtensions.cs:line 42
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at TypeGen.Core.Generator.Services.GenerationSpecProvider.GetGenerationSpec(IEnumerable`1 assemblies) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Core\Generator\Services\GenerationSpecProvider.cs:line 28
   at TypeGen.Core.Generator.Generator.Generate(IEnumerable`1 assemblies) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Core\Generator\Generator.cs:line 341
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Cli\Program.cs:line 137
   at TypeGen.Cli.Program.Main(String[] args) in C:\Dev\Perso\TypeGen\src\TypeGen\TypeGen.Cli\Program.cs:line 70
`

**Comment by jburzynski** [comment]
TypeGenNG is a 3rd party package, it's not related to this project. This package should be used: https://www.nuget.org/packages/TypeGen

**Comment by AHorak** [comment]
Thank you, it works now.
