### ISSUE TITLE
Error when running DotNetCli after tool upgrade

### ISSUE THREAD

**Issue by zarusz** [jburzynski/TypeGen#46]
Hi,

We are running the `dotnet-typegen -v generate` as a post build event script. With every upgrade some of the 3 developers involved get issues that either the DLL or a class was not found and the CLI tool fails. This is the last issue my colleague has after he upgraded from 2.1.0 to 2.1.2 (both the package and cli tool).

```
C:\AppDev\Path\MyProjectName.WebAPI>dotnet-typegen -v generate
Generating files for project “.”...
Reading the config file from “.\tgconfig.json”
Assembly path not found in the config file. Assembly file will be searched for recursively in the project’s bin\.
Could not resolve assembly: MyProjectName.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories:
Could not resolve assembly: MyProjectName.Domain.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories:
Converter ‘PascalCaseToKebabCaseConverter’ not found in assemblies: ‘MyProjectName.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’. Falling back to TypeGen.Core.
Converter ‘PascalCaseToKebabCaseConverter’ found in TypeGen.Core
Converter ‘PascalCaseToCamelCaseConverter’ not found in assemblies: ‘MyProjectName.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’. Falling back to TypeGen.Core.
Converter ‘PascalCaseToCamelCaseConverter’ found in TypeGen.Core
Converter ‘ApiModelsGenerationSpec’ not found in assemblies: ‘MyProjectName.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’. Falling back to TypeGen.Core.
APPLICATION ERROR: Converter ‘ApiModelsGenerationSpec’ not found in TypeGen.Core or any of the assemblies: ‘MyProjectName.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’
  at TypeGen.Cli.Business.TypeResolver.ResolveNoAssembly(String typeName, String typeNameSuffix) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\TypeResolver.cs:line 84
  at TypeGen.Cli.Business.TypeResolver.Resolve(String typeIdentifier, String typeNameSuffix, IEnumerable`1 interfaceConstraints, IEnumerable`1 baseTypeConstraints) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\TypeResolver.cs:line 54
  at TypeGen.Cli.Program.<>c__DisplayClass9_1.<Generate>b__1(String name) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 144
  at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
  at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
  at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
  at TypeGen.Cli.Program.Generate(String projectFolder, String configPath, Boolean verbose) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 143
  at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 75
```

We all have .NET Core 2.1 in similar versions. Here is the `tgconfig.json`:
```
{
  "outputPath": "..\\MyProjectName.WebApp\\ClientApp\\src\\app\\common-services\\models",
  "customTypeMappings": {
    "System.Guid": "string",
    "System.DateTime": "string",
    "System.DateTimeOffset": "string"
  },
  "singleQuotes": true,
  "generationSpecs": [ "ApiModelsGenerationSpec" ],
  "clearOutputDirectory": true
}
```

The `ApiModelsGenerationSpec` is
```
    public class ApiModelsGenerationSpec : GenerationSpec
    {
        public ApiModelsGenerationSpec()
        {
            GetType().Assembly
                .GetTypes()
                .Where(x => x.IsClass && !x.IsAbstract && x.Namespace.StartsWith("MyProjectName.WebAPI.ApiModels", StringComparison.InvariantCulture))
                .ToList()
                .ForEach(x => AddInterface(x));
            //ForAssembly(GetType().Assembly)
            //    .AddInterfaces(@"MyProjectName.WebAPI\.ApiModels\.(.+)");
        }
    }
```

That also fails when my fellow colleague navigates to the project folder using command prompt and executes `dotnet-typegen -v generate`. This is to test it's irrelevant on the post-build. Also we ensured the project DLLs with the spec file are in the `bin` folder.

The weird thing is that I had no issues after upgrading. It also works fine in Azure Pipelines after upgrades. The colleague that has the issue right now, the previous upgrade we made it worked fine for him but failed for another colleague (some non determinism).

We tried:
* Uninstalling the cli tool and installing it (VS and machine was reboot in between)
* Removing all nuget packages 

Have you run into this before or do you have any suggestions?
It feels like there is some caching issue or non deterministic issue after the upgrade.

Thanks,

**Comment by zarusz** [comment]
Yeah, we ensured the project is build/re-built, we ran the CLI tool from command line right after the project was built (and containing the `MyProject.WebApi.dll`). There is something funky going on at times and not sure what exactly. Anyways, will try to try out other ideas in the following days.

Thanks for your help. I will leave this issue open for couple of days - in case we find something.

**Comment by jburzynski** [comment]
I've tried to replicate it in a couple of ways, but with no success.

It would be cool if you could post a solution once you find out what the problem is! Thanks

As a side note, you don't need to (or at least you shouldn't need to) map `System.Guid` to `string` - it's now the default mapping.

Also, if you'd like to change a few things in TypeGen's source code and try with the modified version, you can quickly create new nuget packages with these commands in the root of the repository:

```
version-update.ps1 [old-version] [new-version] - changes TypeGen version (you probably won't need it)
build-publish.ps1 - builds everything
nuget-update.ps1 - creates nuget packages in nuget and nuget-dotnetcli folders
```

Of course you can also just git clone and debug TypeGen.Cli, but with these scripts you don't need to open or configure the IDE.

**Comment by zarusz** [comment]
Today, after returning from vacation I started to experience the issue as well. What is weird is that I did not make any software upgrades. My error is slightly different from the one posted originally.

I will try to get to the bottom of it (somehow).

```

10>MyProject.WebAPI -> C:\Users\tomasz\dev\MyProject.WebAPI\bin\Debug\netcoreapp2.1\MyProject.WebAPI.dll
10>Generate TypeScript models
10>Generating files for project "."...
10>Reading the config file from ".\tgconfig.json"
10>Assembly path not found in the config file. Assembly file will be searched for recursively in the project's bin\.
10>Could not resolve assembly: MyProject.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories:
10>Could not resolve assembly: MyProject.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories:
10>Could not resolve assembly: MyProject.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in any of the searched directories:
10>Converter 'PascalCaseToKebabCaseConverter' not found in assemblies: 'MyProject.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Falling back to TypeGen.Core.
10>Converter 'PascalCaseToKebabCaseConverter' found in TypeGen.Core
10>Converter 'PascalCaseToCamelCaseConverter' not found in assemblies: 'MyProject.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Falling back to TypeGen.Core.
10>Converter 'PascalCaseToCamelCaseConverter' found in TypeGen.Core
10>Converter 'ApiModelsGenerationSpec' found in assembly 'MyProject.WebAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
10>EXEC : GENERIC error : Could not load type 'MyProject.Domain.Core.Enumeration' from assembly 'MyProject.Domain.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
10>   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
10>   at System.Reflection.RuntimePropertyInfo.get_Signature()
10>   at System.Reflection.RuntimePropertyInfo.get_PropertyType()
10>   at TypeGen.Core.Business.TypeService.GetMemberType(MemberInfo memberInfo) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Business\TypeService.cs:line 137
10>   at TypeGen.Core.Business.TypeDependencyService.GetMemberTypeDependencies(Type type) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Business\TypeDependencyService.cs:line 108
10>   at TypeGen.Core.Business.TypeDependencyService.GetTypeDependencies(Type type) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Business\TypeDependencyService.cs:line 48
10>   at TypeGen.Core.Generator.GenerateTypeDependencies(Type type, String outputDir) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 542
10>   at TypeGen.Core.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 347
10>   at TypeGen.Core.Generator.GenerateTypeDependencies(Type type, String outputDir) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 566
10>   at TypeGen.Core.Generator.GenerateClassOrInterface(Type type, ExportTsClassAttribute classAttribute, ExportTsInterfaceAttribute interfaceAttribute) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 347
10>   at TypeGen.Core.Generator.Generate(Type type, Boolean initializeGeneration) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 226
10>   at TypeGen.Core.Generator.<>c__DisplayClass18_0.<Generate>b__3(IEnumerable`1 current, Type type) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 186
10>   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
10>   at TypeGen.Core.Generator.<>c__DisplayClass18_1.<Generate>b__0() in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 177
10>   at TypeGen.Core.Generator.ExecuteWithTypeContextLogging(Action action) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 617
10>   at TypeGen.Core.Generator.Generate(IEnumerable`1 assemblies, Boolean initializeGeneration) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 189
10>   at TypeGen.Core.Generator.<Generate>b__14_0(IEnumerable`1 acc, KeyValuePair`2 kvp) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 121
10>   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
10>   at TypeGen.Core.Generator.Generate(GenerationSpec generationSpec) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Generator.cs:line 120
10>   at TypeGen.Cli.Program.<>c__DisplayClass9_0.<Generate>b__4(IEnumerable`1 acc, GenerationSpec spec) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 147
10>   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
10>   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath, Boolean verbose) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 143
10>   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 75
```

**Comment by cederlof** [comment]
I have the same(?) problem with a .NET Core 2.2-class project:

```
PS> dotnet-typegen generate -v

Generating files for project "."...
Reading the config file from ".\tgconfig.json"
Assembly path not found in the config file. Assembly file will be searched for recursively in the project's bin\.
Converter 'PascalCaseToKebabCaseConverter' not found in assemblies: 'ESS.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Falling back to TypeGen.Core.
Converter 'PascalCaseToKebabCaseConverter' found in TypeGen.Core
Converter 'PascalCaseToCamelCaseConverter' not found in assemblies: 'ESS.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Falling back to TypeGen.Core.
Converter 'PascalCaseToCamelCaseConverter' found in TypeGen.Core
Converter 'EssModelGenerationSpec' not found in assemblies: 'ESS.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Falling back to TypeGen.Core.
APPLICATION ERROR: Converter 'EssModelGenerationSpec' not found in TypeGen.Core or any of the assemblies: 'ESS.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at TypeGen.Cli.Business.TypeResolver.ResolveNoAssembly(String typeName, String typeNameSuffix) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\TypeResolver.cs:line 84
   at TypeGen.Cli.Business.TypeResolver.Resolve(String typeIdentifier, String typeNameSuffix, IEnumerable`1 interfaceConstraints, IEnumerable`1 baseTypeConstraints) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\TypeResolver.cs:line 54
   at TypeGen.Cli.Program.<>c__DisplayClass9_1.<Generate>b__1(String name) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 144
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath, Boolean verbose) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 143
   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 75
```

It can't find my GenerationSpec-class.

**Comment by jburzynski** [comment]
So to sum up, there are 2 types of errors:

- GenerationSpec **not found** in assembly (posted by @cederlof and also mentioned by @zarusz (happens to his colleagues))
- GenerationSpec **found** in assembly, but a class specified in the spec is not found (happened to @zarusz)

I tried some more scenarios to replicate this error, but they don't seem to cover the case in which the error happens:

- changed dotnet tool version to 2.1.0 and project's TypeGen version to 2.1.3
- changed dotnet tool version to 2.1.3 and project's TypeGen version to 2.1.0
- used TypeGen on a netcoreapp2.2 (TypeGen is netcoreapp2.1, so I thought maybe this is the reason, but when I tried it I didn't get the error)

@cederlof just to rule this out: have you built your project before running TypeGen?

**Comment by zarusz** [comment]
I was able to pinpoint my most recent issue (which @jburzynski classifies as 2nd), but still haven't tested if it solves the issue for my colleague (1st issue).

Note, the TS generation on the Azure DevOps build pipelines works all the time without any issues.

So here is my setup that was working initially, but then stopped working:
1. `MyProject.WebApi` has `ApiModels` namespace with all the C# models I want to generate to TS
2. These C# models were referencing 2 classes from `MyProject.Domain` assembly.
3. Furthermore, these domain classes were referencing another class `MyProject.Domain.Core.Enumeration` (coming from `MyProject.Domain.Core` assembly) which was not found.

I checked few things (as admin and non admin account):
1. Built the WebApi project and ensured all the DLLs are there and even used DotPeek to check if the supposedly missing classes did indeed exist. And yes, all classes did exist.
2. Ran the `dotnet-typegen` cli from command prompt. And yes, I got the same error from the CLI tool.

Being clueless as to what is going on, I refactored my models to the the desired end state where my `ApiModels` no longer reference classes from any other assembly.
And guess, what it did fix the issue.

Now, I have no idea, why it was working before and suddenly stopped working on my local. Similar issues happened to other two of my colleagues before. The first one I did not captured, for the second colleague the error is stated in my first message on this issue. What is common to all 3 of us, is that one day it stopped working (at different point in times).

I can only suspect there is something funky around loading transitive dependencies from the assembly containing the spec class inside the global dotnet tool - not necessary related with the TypeGen.

I guess, since the refactor brought me to the desired state and the CLI tool is working then I consider my issue as resolved.

**Comment by jburzynski** [comment]
Yeah it's hard to say what the problem is here. I'll try to replicate it some more and post any progress here in this thread. I'll leave it open for a while just in case.

**Comment by cederlof** [comment]
> @cederlof just to rule this out: have you built your project before running TypeGen?

I did.

I just found my problem though, and it might not be related. After having upgraded .NET Core to 2.2 I had still directories of 2.1 in my bin, and using several different build configurations the auto-lookup picked an assembly not containing the bits... I tried specifying the assembly myself also, but must have picked the wrong build-configuration. Sorry about that.

It would have been helpful if the verbose-setting would write the full path to the used dll and not only the assembly name, as that might have put me on the right track.

Thanks for a great lib!

**Comment by jburzynski** [comment]
That could be useful - I'll add this to the next release. Glad you like the lib!

It did cross my mind that it could be picking up a dll from a different build target, but I think the error that @zarusz gets is different, because it persists even with a clean solution build.

It's good that your error got resolved though!

**Comment by jburzynski** [comment]
I added logging resolved dll paths (with verbose option) in the latest version.

I'm closing this issue due to inactivity.

**Comment by vladkasianenko** [comment]
Remove folder from "C:\Users\<your_user_name>\.nuget\packages\<your-package>" and rerun again. For some reason TypeGen is trying to find an assembly in the nuget folder first.

**Comment by MaximG1234** [comment]
FYI @jburzynski or others that might run into this issue.

I have just run into the same problem after upgrading my project from .NET 7 to .NET 8. 

My bin folder still had the .NET 7 folder/binaries in it and after deleting the problem resolved.
