### ISSUE TITLE
Getting Wrong parameter error when trying to generate

### ISSUE THREAD

**Issue by PSausM** [jburzynski/TypeGen#93]
Hi
When I try to generate my classes I get this error on the output window.

GENERIC ERROR: Falscher Parameter. : 'C:\Users\Paul\Source\repos\Resy\scr\Server\Server.csproj'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path)
   at TypeGen.Core.Storage.FileSystem.GetDirectoryFiles(String directory) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Core\Storage\FileSystem.cs:line 59
   at TypeGen.Cli.Business.ConfigProvider.GetDefaultAssemblyPath(String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 100
   at TypeGen.Cli.Business.ConfigProvider.GetAssemblyPath(String configAssemblyPath, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 95
   at TypeGen.Cli.Business.ConfigProvider.UpdateConfigAssemblyPaths(TgConfig config, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 75
   at TypeGen.Cli.Business.ConfigProvider.GetConfig(String configPath, String projectFolder) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Business\ConfigProvider.cs:line 48
   at TypeGen.Cli.Program.Generate(String projectFolder, String configPath) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 112
   at TypeGen.Cli.Program.Main(String[] args) in D:\Google Drive\Projects\type-gen\src\TypeGen\TypeGen.Cli\Program.cs:line 70

**Comment by jburzynski** [comment]
Hi,
sorry for a late response.

Thanks for reporting,

Usually I do some work on TypeGen when I have some free time.
But since lately I don't have a lot of free time for TypeGen, I think the best way for fixing issues quickly is to try to make a PR so that I could merge it later (I know, it's not the ideal solution, because it requires learning the code etc., but at the moment it seems like the best way).

Once you fork `jburzynski/TypeGen` and make the necessary changes (I'd suggest using the `master` branch, because it always has the current stable code), you can then create a `TypeGen` (and `dotnet-typegen`) NuGet package to use in your custom NuGet feed.
To create such NuGet package, you'd need to run these 3 scripts which are in the root directory of the repository:

- `version-update.ps1 [old TypeGen version] [new TypeGen version]` - changes the version metadata (in the code, NuGet packages etc.) (example: `./version-update.ps1 2.4.0 2.4.1`)
- `build-publish.ps1` - (pretty self-explanatory :) ) builds and publishes the project(s)
- `nuget-update.ps1` - updates the NuGet packages in the `nuget` and `nuget-dotnetcli` folders

One possible scenario is using your package from your custom NuGet feed until the new version is "officially" released.
When the new version is released, all you'd need to do is change the feed so that the "official" package is used.

I hope this helps :)

**Comment by jburzynski** [comment]
I have just looked into the error and it seems that the reason this may be happening is because the `-p|--project-folder` parameter is set to the project (`csproj`) file instead of the project's folder.

If this is the case, then maybe specifying the project folder (`C:\Users\Paul\Source\repos\Resy\scr\Server`) could help.

The command would look like this:
`[dotnet-]typegen -p "C:\Users\Paul\Source\repos\Resy\scr\Server" generate`

I hope this helps.

**Comment by jburzynski** [comment]
Closed due to inactivity
